### ISSUE TITLE
Unable to make this work with a simple example

### ISSUE THREAD

**Issue by brekk** [zkochan/remark-mos#1]
Hi there,

I'm really excited to be potentially using this library, but I'm running into some issues running this in the REPL:

``` javascript
const remark = require('remark')
const mos = require('remark-mos')
remark()
  .use(mos, {scope: {foo: () => `butts`}, useStrict: true})
  .process(`<!--@foo()--><!--/@-->`, console.log.bind(console))
```

I am seeing no change in the outcome data, but was expecting to see `<!--@foo()-->butts<!--/@-->`in the outcome.

Am I misusing this? Per the examples, it seems like maybe the `remark` library used to return Promises instead of the current callback approach?

Thanks,

Brekk

**Comment by zkochan** [comment]
Because you try to do it with `remark`

I had to make a fork of remark... In the readme example you can see that `@zkochan/remark` is used.

But better use just [mos](https://github.com/mosjs/mos). I don't maintain this package anymore. `mos` does the same and more.

**Comment by brekk** [comment]
@zkochan Thanks for your time!
